name: PlatformIO CI

on:
  push:
    tags:
      - "v*"  # Runs only when pushing a version tag like "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Extract Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Store Firmware as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-${{ env.VERSION }}.bin
          path: .pio/build/esp32doit-devkit-v1/firmware.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: "Automated release of firmware version ${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: .pio/build/esp32doit-devkit-v1/firmware.bin
